Script started on 2023-02-06 20:01:38-05:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="80" LINES="66"]
]0;zs35@gold03: ~/Desktop/214/labs/05[01;32mzs35@gold03[00m:[01;34m~/Desktop/214/labs/05[00m$ clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> ((fn [x y z][x y z] (+ x y z)(+ x y z))user=> ((fn [x y z] (+ x y z)) 3 4 5)user=> ((fn [x y z] (+ x y z)) 3 4 5)user=> [K((fn [x y z] (+ x y z)) 3 4 5)
[K12
user=> [Kuser=> [Kuser=> ((fn [x][x] (nil? x)(nil? x))user=> ((fn [x] (nil? x)) nil)user=> ((fn [x] (nil? x)) nil)user=> [K((fn [x] (nil? x)) nil)
true
user=> [Kuser=> [Kuser=> ((fn [x][x] (nil? x)(nil? x))user=> ((fn [x] (nil? x)) 0)user=> ((fn [x] (nil? x)) 0)user=> [K((fn [x] (nil? x)) 0)
false
user=> [Kuser=> [Kuser=> (fn [][] 17.2)user=> (fn [] 17.2)user=> [K(fn [] 17.2)
#object[user$eval148$fn__149 0xc81fd12 "user$eval148$fn__149@c81fd12"]
user=> [Kuser=> [Kuser=> ((fn [][] 17.2)user=> ((fn [] 17.2))user=> ((fn [] 17.2))user=> [K((fn [] 17.2))
17.2
user=> [Kuser=> [Kuser=> 
[K]0;zs35@gold03: ~/Desktop/214/labs/05[01;32mzs35@gold03[00m:[01;34m~/Desktop/214/labs/05[00m$ exit

Script done on 2023-02-06 20:02:20-05:00 [COMMAND_EXIT_CODE="0"]
