Script started on 2023-02-13 23:19:52-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="68"]
]0;zs35@gold03: ~/Desktop/214/projects/05/clojure[01;32mzs35@gold03[00m:[01;34m~/Desktop/214/projects/05/clojure[00m$ cd src
]0;zs35@gold03: ~/Desktop/214/projects/05/clojure/src[01;32mzs35@gold03[00m:[01;34m~/Desktop/214/projects/05/clojure/src[00m$ cat member  .clj
;;;; member.clj checks if an element is in a list.
;;;;
;;;; Input: n, an item; n-sequence, a sequence of items
;;;; Output: True or False, boolean value
;;;;
;;;; Student Name: ZeAi Sun
;;;; Date: Feb 9, 2023
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(ns member)                            ; name the program

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; member?() recursively checks if an item is in a list.
;;; Receive: n, an item; n-sequence, a sequence of items
;;; Output: True or False, boolean value
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defn member? [n [n-sequence]]
    (if (= n (first n-sequence))                    ; if the current item is the target item
        true                                        ; return true
        (if (= 1 (count n-sequence))                ; otherwise, check if the current item is the only item in the list
            false                                   ; if so, return false
            (member? n (list (rest n-sequence)))    ; if not, recursively call the funtion on the rest of the list
        )
    )
)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; -main is a 'driver' for the member?() functions.
;;; Input: n, an item; n-sequence, a sequence of items
;;; Output: True or False, boolean value
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defn -main []
 (print "To check if an item is in a list, input an item and a sequence: ") (flush)
 (let
    [ n (int (read)) 
      n-seq (sequence (read))] 
    (println (member? n [n-seq]))
 )
)]0;zs35@gold03: ~/Desktop/214/projects/05/clojure/src[01;32mzs35@gold03[00m:[01;34m~/Desktop/214/projects/05/clojure/src[00m$ c clojure -m mme  ember
To check if an item is in a list, input an item and a sequence: 1 (1 2 3)
true
]0;zs35@gold03: ~/Desktop/214/projects/05/clojure/src[01;32mzs35@gold03[00m:[01;34m~/Desktop/214/projects/05/clojure/src[00m$ 4 (   clojure -m member
To check if an item is in a list, input an item and a sequence: ( 4 (1 2 3)
false
]0;zs35@gold03: ~/Desktop/214/projects/05/clojure/src[01;32mzs35@gold03[00m:[01;34m~/Desktop/214/projects/05/clojure/src[00m$ e exit

Script done on 2023-02-13 23:20:19-05:00 [COMMAND_EXIT_CODE="0"]
