Script started on 2023-02-13 23:20:30-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="68"]
]0;zs35@gold03: ~/Desktop/214/projects/05/clojure[01;32mzs35@gold03[00m:[01;34m~/Desktop/214/projects/05/clojure[00m$ cd src
]0;zs35@gold03: ~/Desktop/214/projects/05/clojure/src[01;32mzs35@gold03[00m:[01;34m~/Desktop/214/projects/05/clojure/src[00m$ cat sb ubsequence.clj
;;;; subsequence.clj returns the indicated subsequence.
;;;;
;;;; Input: n-sequence, a sequence of items; i and n, both integers
;;;; Output: result, a sequence of items
;;;;
;;;; Student Name: ZeAi Sun
;;;; Date: Feb 9, 2023
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(ns subsequence)                            ; name the program

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; subsequence() recursively returns the indicated subsequence.
;;; Receive: n-sequence, a sequence of items; i and n, both integers
;;; Output: result, a sequence of items
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defn subsequence [[n-sequence] i n]
    (if (or (or (= 0 (count n-sequence)) (> i (count n-sequence))) (> (+ i n) (count n-sequence)))  ; if param is invalid, return nil
        nil
        (do                             ; if params are all valid, recursively run the function
            (if (= n 0)
                nil
                (cons (nth n-sequence i) (subsequence [n-sequence] (+ i 1) (- n 1)))
            )
        )
    )
)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; -main is a 'driver' for the subsequence() functions.
;;; Input: n-sequence, a sequence of items; i and n, both integers
;;; Output: result, a sequence of items
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defn -main []
 (print "Input the sequence, i and n: ") (flush)
 (let
    [ n-seq (sequence(read))
      i (int (read)) 
      n (int (read)) ] 
    (println (subsequence [n-seq] i n))
 )
)]0;zs35@gold03: ~/Desktop/214/projects/05/clojure/src[01;32mzs35@gold03[00m:[01;34m~/Desktop/214/projects/05/clojure/src[00m$ clojure -m subsequence
Input the sequence, i and n: (1 23    3 4 5) 1   0 5
(1 2 3 4 5)
]0;zs35@gold03: ~/Desktop/214/projects/05/clojure/src[01;32mzs35@gold03[00m:[01;34m~/Desktop/214/projects/05/clojure/src[00m$ clojure -m subsequence
Input the sequence, i and n: (1 2 3 4 5) 0 10
nil
]0;zs35@gold03: ~/Desktop/214/projects/05/clojure/src[01;32mzs35@gold03[00m:[01;34m~/Desktop/214/projects/05/clojure/src[00m$ clojure -m subsequence
Input the sequence, i and n: (1 2 4   3 4 5) 1 1  0 0 5
nil
]0;zs35@gold03: ~/Desktop/214/projects/05/clojure/src[01;32mzs35@gold03[00m:[01;34m~/Desktop/214/projects/05/clojure/src[00m$ clojure -m subsequence
Input the sequence, i and n: () 1 4
nil
]0;zs35@gold03: ~/Desktop/214/projects/05/clojure/src[01;32mzs35@gold03[00m:[01;34m~/Desktop/214/projects/05/clojure/src[00m$ clojure -m subsequence
Input the sequence, i and n: (1 2 3 4 5 6 7) 2 4
(3 4 5 6)
]0;zs35@gold03: ~/Desktop/214/projects/05/clojure/src[01;32mzs35@gold03[00m:[01;34m~/Desktop/214/projects/05/clojure/src[00m$ exit

Script done on 2023-02-13 23:21:40-05:00 [COMMAND_EXIT_CODE="0"]
